# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-24 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=256, verbose_name='收藏地点')),
                ('line_origin', models.CharField(max_length=256, verbose_name='收藏路线起点')),
                ('line_destination', models.CharField(max_length=256, verbose_name='收藏路线终点')),
            ],
            options={
                'verbose_name_plural': '收藏',
                'db_table': 'collect',
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=256, verbose_name='搜索历史')),
            ],
            options={
                'verbose_name_plural': '搜索历史',
                'db_table': 'searchhistory',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='headimages')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('nickname', models.CharField(max_length=32, verbose_name='昵称')),
                ('sex', models.BooleanField(default=True, verbose_name='性别')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('phone', models.CharField(max_length=32, verbose_name='手机号')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('token', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='s_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.User', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='collect',
            name='c_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.User', verbose_name='收藏用户'),
        ),
    ]
