# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-16 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='line_destination',
            field=models.CharField(default=None, max_length=256, verbose_name='收藏路线终点'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='line_origin',
            field=models.CharField(default=None, max_length=256, verbose_name='收藏路线起点'),
        ),
        migrations.AlterField(
            model_name='collect',
            name='site',
            field=models.CharField(default=None, max_length=256, verbose_name='收藏地点'),
        ),
    ]
