# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-05-16 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_auto_20190516_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(default=None, max_length=256, verbose_name='收藏地点')),
                ('s_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.User', verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '收藏地点',
                'db_table': 'site',
            },
        ),
        migrations.RemoveField(
            model_name='searchhistory',
            name='s_user',
        ),
        migrations.AlterModelOptions(
            name='collect',
            options={'verbose_name_plural': '收藏路线'},
        ),
        migrations.RemoveField(
            model_name='collect',
            name='site',
        ),
        migrations.AlterField(
            model_name='collect',
            name='c_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.User', verbose_name='用户'),
        ),
        migrations.DeleteModel(
            name='SearchHistory',
        ),
    ]
